# Generated by Django 5.2.8 on 2025-11-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("middle_name", models.CharField(max_length=60)),
                ("ssn", models.CharField(max_length=12)),
                (
                    "date_of_birth",
                    models.DateField(
                        choices=[
                            ("Married", "Married"),
                            ("Separated", "Separated"),
                            ("Single", "Single"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=60,
                    ),
                ),
                ("citizenship", models.CharField(max_length=60)),
                (
                    "type_of_credit",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Joint", "Joint")],
                        max_length=30,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Married", "Married"),
                            ("Separated", "Separated"),
                            ("Single", "Single"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("dependents", models.SmallIntegerField()),
                ("dependent_ages", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Checking", "Checking"),
                            ("Savings", "Savings"),
                            ("Money Market", "Money Market"),
                            ("Certificate of Deposit", "Certificate of Deposit"),
                            ("Mutual Fund", "Mutual Fund"),
                            ("Stocks", "Stocks"),
                            ("Stock Options", "Stock Options"),
                            ("Bonds", "Bonds"),
                            ("Retirement", "Retirement"),
                            ("Bridge Loan Proceeds", "Bridge Loan Proceeds"),
                            (
                                "Individual Development Account",
                                "Individual Development Account",
                            ),
                            ("Trust Account", "Trust Account"),
                            (
                                "Cash Value of Life Insurance",
                                "Cash Value of Life Insurance",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("financial_institution", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("cash_market_value", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=150)),
                ("unit", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "address_type",
                    models.CharField(
                        choices=[("Current", "Current"), ("Former", "Former")],
                        max_length=20,
                    ),
                ),
                ("years_at", models.SmallIntegerField()),
                ("months_at", models.SmallIntegerField()),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("Own", "Own"),
                            ("Rent", "Rent"),
                            (
                                "No primary housing expense",
                                "No primary housing expense",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("rent_per_month", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupy_as_primary_residence", models.BooleanField()),
                ("has_relationship_with_seller", models.BooleanField()),
                ("is_borrowing_from_other_party", models.BooleanField()),
                ("is_applying_for_another_mortgage", models.BooleanField()),
                ("is_applying_for_new_credit", models.BooleanField()),
                ("is_subject_to_a_lien", models.BooleanField()),
                ("is_cosigner_or_guarantor_on_undisclosed_debt", models.BooleanField()),
                ("is_any_other_judgements", models.BooleanField()),
                ("has_law_suit_with_potential_liability", models.BooleanField()),
                (
                    "has_conveyed_title_in_lieu_of_forclosure_last_7_years",
                    models.BooleanField(),
                ),
                ("has_declared_bankrupcy_with_past_7_years", models.BooleanField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_name", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "employer_type",
                    models.CharField(
                        choices=[("Current", "Current"), ("Previous", "Previous")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("previous_gross_monthly_income", models.FloatField()),
                ("is_owned", models.BooleanField()),
                ("base_pay_per_month", models.FloatField()),
                ("overtime_pay_per_month", models.FloatField()),
                ("bonus_per_month", models.FloatField()),
                ("commission_per_month", models.FloatField()),
                ("military_entitlements_per_month", models.FloatField()),
                ("other_pay_per_month", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        choices=[
                            ("Alimony", "Alimony"),
                            ("Automobile Allowance", "Automobile Allowance"),
                            ("Boarder Income", "Boarder Income"),
                            ("Capital Gains", "Capital Gains"),
                            ("Child Support", "Child Support"),
                            ("Disability", "Disability"),
                            ("Foster Care", "Foster Care"),
                            ("Housing", "Housing"),
                            ("Parsonage", "Parsonage"),
                            ("Interest and Dividends", "Interest and Dividends"),
                            (
                                "Mortgage Credit Certificate",
                                "Mortgage Credit Certificate",
                            ),
                            ("Mortgage Differential", "Mortgage Differential"),
                            ("Payments", "Payments"),
                            ("Notes Receivable", "Notes Receivable"),
                            ("Public Assistance", "Public Assistance"),
                            ("Pension", "Pension"),
                            ("IRA", "IRA"),
                            ("Royalty Payments", "Royalty Payments"),
                            ("Separate Maintenance", "Separate Maintenance"),
                            ("Social Security", "Social Security"),
                            ("Trust", "Trust"),
                            ("Unemployment", "Unemployment"),
                            ("VA Compensation", "VA Compensation"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("monthly_income", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Revolving", "Revolving"),
                            ("Installment", "Installment"),
                            ("Open 30-Day", "Open 30-Day"),
                            ("Lease", "Lease"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("unpaid_balance", models.FloatField()),
                ("paid_off_before_or_at_closing", models.BooleanField()),
                ("monthly_payment", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanPropertyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.FloatField()),
                (
                    "loan_purpose",
                    models.CharField(
                        choices=[
                            ("Purchase", "Purchase"),
                            ("Refinance", "Refinance"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("other_purpose", models.CharField(max_length=100)),
                ("property_address", models.CharField(max_length=150)),
                ("property_unit", models.CharField(max_length=100)),
                ("property_city", models.CharField(max_length=100)),
                (
                    "property_state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("property_zip_code", models.CharField(max_length=20)),
                ("property_country", models.CharField(max_length=100)),
                ("property_number_of_units", models.IntegerField()),
                ("property_value", models.FloatField()),
                (
                    "occupancy",
                    models.CharField(
                        choices=[
                            ("Primary Residence", "Primary Residence"),
                            ("Second Home", "Second Home"),
                            ("Investment Property", "Investment Property"),
                            ("FHA Secondary Home", "FHA Secondary Home"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_mixed_use_of_property", models.BooleanField()),
                ("is_manufactured_home", models.BooleanField()),
                ("expected_rental_income", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Cash Gift", "Cash Gift"),
                            ("Gift of Equity", "Gift of Equity"),
                            ("Grant", "Grant"),
                        ],
                        max_length=100,
                    ),
                ),
                ("deposited", models.BooleanField()),
                ("not_deposited", models.BooleanField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Community Nonprofit", "Community Nonprofit"),
                            ("Employer", "Employer"),
                            ("Federal Agency", "Federal Agency"),
                            ("Local Agency", "Local Agency"),
                            ("Relative", "Relative"),
                            ("Religious Nonprofit", "Religious Nonprofit"),
                            ("State Agency", "State Agency"),
                            ("Unmarried Partner", "Unmarried Partner"),
                            ("Lender", "Lender"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cash_market_value", models.FloatField()),
                (
                    "loan_property_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loanpropertyinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherAssetsCreditsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_credit_type",
                    models.CharField(
                        choices=[
                            (
                                "Proceeds from Real Estate Property to be sold on or before closing",
                                "Other Asset Proceeds From Real Estate",
                            ),
                            (
                                "Proceeds from Sale of Non-Real Estate Asset",
                                "Other Asset Proceeds From Non Real Estate",
                            ),
                            (
                                "Secured Borrowed Funds",
                                "Other Asset Secured Borrowed Funds",
                            ),
                            (
                                "Unsecured Borrowed Funds",
                                "Other Asset Unsecured Borrowed Funds",
                            ),
                            ("Other", "Other Asset"),
                            ("Earnest Money", "Earnest Money"),
                            ("Employer Assistance", "Employer Assistance"),
                            ("Lot Equity", "Lot Equity"),
                            ("Relocation Funds", "Relocation Funds"),
                            ("Rent Credit", "Rent Credit"),
                            ("Sweat Equity", "Sweat Equity"),
                            ("Trade Equity", "Trade Equity "),
                        ],
                        max_length=100,
                    ),
                ),
                ("cash_market_value", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherLiabilityExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liability_expense_type",
                    models.CharField(
                        choices=[
                            ("Alimony", "Alimony"),
                            ("Child Support", "Child Support"),
                            ("Separate Maintenance", "Separate Maintenance"),
                            ("Job Related Expenses", "Job Related Expenses"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("monthly_paymnet", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("phone_number_type", models.CharField(max_length=10)),
                ("phone_number_ext", models.CharField(max_length=10)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=150)),
                ("unit", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("property_value", models.FloatField()),
                ("monthly_insurance_tax_association_due", models.FloatField()),
                ("monthly_rental_income", models.FloatField()),
                ("net_monthly_rental_income", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateProperyMortgageLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creditor_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("monthly_mortgage_payment", models.FloatField()),
                ("unpaid_balance", models.FloatField()),
                ("paid_off_before_or_at_closing", models.BooleanField()),
                (
                    "mortgage_loan_type",
                    models.CharField(
                        choices=[
                            ("FHA", "FHA"),
                            ("Conventional", "Conventional"),
                            ("USDA-RD", "USDA-RD"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("credit_limit", models.FloatField()),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.borrower"
                    ),
                ),
                (
                    "real_estate_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.realestateproperty",
                    ),
                ),
            ],
        ),
    ]
