# Generated by Django 5.2.8 on 2025-11-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="ethicity",
            field=models.CharField(
                choices=[
                    ("Hispanic or Latino", "Hispanic or Latino"),
                    ("Not Hispanic or Latino", "Not Hispanic or Latino"),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="borrower",
            name="race",
            field=models.CharField(
                choices=[
                    (
                        "American Indian or Alaskan Native",
                        "American Indian or Alaskan Native",
                    ),
                    ("Black or African American", "Black or African American"),
                    ("Asian Indian", "Asian Indian"),
                    ("Chinese", "Chinese"),
                    ("Filipino", "Filipino"),
                    ("Japanese", "Japanese"),
                    ("Korean", "Korean"),
                    ("Vietnamese", "Vietnamese"),
                    (
                        "Native Hawaiian or Other Pacific Islander",
                        "Native Hawaiian or Other Pacific Islander",
                    ),
                    ("White", "White"),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="rent_per_month",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="unit",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="citizenship",
            field=models.CharField(
                choices=[
                    ("US Citizen", "US Citizen"),
                    ("Permanent Resident Alien", "Permanent Resident Alien"),
                    ("Non Permanent Resident Alien", "Non Permanent Resident Alien"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="dependent_ages",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="dependents",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="middle_name",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="employment",
            name="unit",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
