# Generated by Django 5.2.8 on 2025-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_borrower_ethicity_borrower_race_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=30,
                null=True,
            ),
        ),
    ]
