# Generated by Django 5.2.8 on 2025-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_borrower_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number_type",
            field=models.CharField(
                choices=[("Home", "Home"), ("Cell", "Cell"), ("Work", "Work")],
                max_length=10,
            ),
        ),
    ]
