# Generated by Django 5.2.8 on 2025-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_phonenumber_phone_number_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="dependent_ages",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="dependents",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="middle_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number_ext",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
