# Generated by Django 5.2.8 on 2025-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_borrower_dependent_ages_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OtherLiabilityExpenses",
            new_name="OtherLiabilityExpense",
        ),
        migrations.AlterField(
            model_name="address",
            name="rent_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
