# Generated by Django 5.2.8 on 2025-11-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_otherliabilityexpenses_otherliabilityexpense_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
    ]
