# Generated by Django 5.2.8 on 2025-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liability",
            options={"verbose_name": "Liability", "verbose_name_plural": "Liabilities"},
        ),
        migrations.AlterModelOptions(
            name="loanpropertyinfo",
            options={"verbose_name": "Loan Property Information"},
        ),
        migrations.AlterModelOptions(
            name="otherliabilityexpense",
            options={
                "verbose_name": "Other Liability Expense",
                "verbose_name_plural": "Other Liability Expenses",
            },
        ),
        migrations.AlterModelOptions(
            name="realestateproperty",
            options={
                "verbose_name": "RealEstateProperty",
                "verbose_name_plural": "Real Estate Properties",
            },
        ),
        migrations.AlterField(
            model_name="employment",
            name="unit",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
