# Generated by Django 5.2.8 on 2025-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_liability_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
