# Generated by Django 5.2.8 on 2025-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_employment_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="bonus_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employment",
            name="commission_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employment",
            name="military_entitlements_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employment",
            name="other_pay_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employment",
            name="overtime_pay_per_month",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
